#!/usr/bin/env python3
"""Reproducibly render or verify the Stage 17 preflight policy v13."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import pathlib
import sys
from typing import Any

import stage17_read_only_preflight_semantic_verifier_v13 as verifier
import stage17_state_journal as journal


def canonical(document: object) -> bytes:
    return (json.dumps(document, sort_keys=True, separators=(",", ":")) + "\n").encode()


def binding(root: pathlib.Path, relative: str) -> dict[str, Any]:
    payload = (root / relative).read_bytes()
    return {"path": relative, "size_bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest()}


def render(root: pathlib.Path) -> dict[str, Any]:
    predecessor_path = verifier.POLICY_V12_PATH
    policy = copy.deepcopy(json.loads((root / predecessor_path).read_text()))
    graph_path = root / "config/stage17/stage17-operational-graph-definition-v1.json"
    catalog_path = root / "config/stage17/stage17-external-input-catalog-v1.json"
    genesis_path = root / "config/stage17/journal/stage17-state-journal-000000.json"
    genesis = json.loads(genesis_path.read_text())
    policy.update({
        "schema_version":
            "cpu-prefetch-stage17-read-only-preflight-evidence-admission-policy/13",
        "policy_id": "STAGE17-READ-ONLY-PREFLIGHT-EVIDENCE-ADMISSION-POLICY-v13",
        "policy_version": "13",
        "predecessor": {
            "policy_v12": binding(root, predecessor_path),
            "adr_0122": binding(root, verifier.ADR_0122_PATH),
            "graph_sha256": hashlib.sha256(graph_path.read_bytes()).hexdigest(),
            "catalog_sha256": hashlib.sha256(catalog_path.read_bytes()).hexdigest(),
            "genesis_file_sha256": hashlib.sha256(genesis_path.read_bytes()).hexdigest(),
            "genesis_record_sha256": genesis["genesis"]["genesis_sha256"],
            "resolution_schema_sha256": journal.version_hashes(root)[
                "resolution_schema_sha256"
            ],
        },
        "schema_bindings": [binding(root, item) for item in verifier.SCHEMA_PATHS],
        "fixed_action_plan": binding(root, verifier.EFFECTIVE_ACTION_PLAN_PATH),
        "successor_action_plan": binding(root, verifier.SUCCESSOR_ACTION_PLAN_PATH),
        "implementations": {
            name: binding(root, path)
            for name, path in verifier.IMPLEMENTATION_PATHS.items()
        },
    })
    policy["entries"][0] = {
        "input_id": "S17-EXT-001", "status": "IMPLEMENTED",
        "verifier_id": verifier.VERIFIER_ID,
        "verifier_version": verifier.VERIFIER_VERSION,
    }
    return policy


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path,
                        default=pathlib.Path(__file__).parents[1])
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    if arguments.check and arguments.write:
        parser.error("--check and --write are mutually exclusive")
    root = arguments.root.resolve()
    payload = canonical(render(root))
    destination = root / verifier.POLICY_PATH
    if arguments.check:
        if not destination.is_file() or destination.read_bytes() != payload:
            print("stage17-preflight-policy-v13: FAIL: generated bytes drifted",
                  file=sys.stderr)
            return 1
        print("stage17-preflight-policy-v13: PASS")
        return 0
    if arguments.write:
        temporary = destination.with_name(destination.name + ".tmp")
        descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL |
                             os.O_CLOEXEC, 0o644)
        try:
            os.write(descriptor, payload)
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        os.replace(temporary, destination)
        directory = os.open(destination.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
        print(f"stage17-preflight-policy-v13: PASS written={destination}")
        return 0
    sys.stdout.buffer.write(payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
